#!/bin/bash
#
# Copyright 2026 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -z "${DIB_TARBALL_PATH:-}" ]; then
    echo "ERROR: DIB_TARBALL_PATH must be set to the path of an OS root filesystem tarball."
    exit 1
fi

if [ ! -f "${DIB_TARBALL_PATH}" ]; then
    echo "ERROR: DIB_TARBALL_PATH '${DIB_TARBALL_PATH}' does not exist or is not a file."
    exit 1
fi

echo "Extracting ${DIB_TARBALL_PATH} into ${TARGET_ROOT}"
sudo tar -C ${TARGET_ROOT} --numeric-owner -xf ${DIB_TARBALL_PATH}

sudo rm -f ${TARGET_ROOT}/.extra_settings
