#!/bin/bash
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)

IMAGE_PATHS="/usr/share/ipxe/ipxe.lkrn /usr/lib/ipxe/ipxe.lkrn"

for _FILE in $IMAGE_PATHS ; do
    if [ -s $_FILE ]; then
        cp $_FILE /boot
    fi
done

cat << EOF >>/etc/grub.d/40_custom
menuentry "iPXE boot" {
linux16 /boot/ipxe.lkrn
}
EOF
sed -i -e 's/^GRUB_TIMEOUT.*/GRUB_TIMEOUT=60/' /etc/default/grub
sed -i -e 's/^GRUB_DEFAULT.*/GRUB_DEFAULT="iPXE boot"/' /etc/default/grub

cat /etc/default/grub
cat /etc/grub.d/40_custom

